#!/bin/bash

function usage() {
  cat <<EOM
Usage: $(basename "$0") [OPTION]...

    -p          Run Pacman only
    -h          Show help

EOM
}

while (($#>0)); do
  case $1 in
    p|-p|--pacman)
      PACUP_MOD="pacman"
      ;;
    h|-h|--help)
      usage
      exit 0
      ;;
    *)
      usage
      exit 1
      ;;
  esac
  shift
done


function PACUP_PACMAN() {
  echo -e "\nUpdating Pacman packages..."
  sudo pacman -Syu
  echo -e "\nRemoving no-needed Pacman packages..."
  sudo pacman -Rns $(pacman -Qtdq)  
}

function PACUP_SYS() {
  if [ $(command -v snap) ]; then
    echo -e "\nUpdating Snap packages..."
    sudo snap refresh
  fi
  if [ $(command -v flatpak) ]; then
    echo -e "\nUpdating Flatpak packages..."
    sudo flatpak update
  fi
}

function PACUP_AUR_ROOT() {
  if [ "$(whoami)" == "root" ]; then
    echo -e "\nBecause you are running as root, the AUR operation is skipped."
    echo -e "\nDone!"
    exit 0
  fi
  PACUP_AUR
}

function PACUP_AUR() {
  if [ $(command -v yay) ]; then
    echo -e "Updating AUR packages..."
    yay -Sayu
  fi
  if [ $(command -v paru) ]; then
    echo -e "Updating AUR packages..."
    paru -Sayu
  fi
  if [ $(command -v pacaur) ]; then
    echo -e "Updating AUR packages..."
    pacaur -Sayu
  fi
  if [ $(command -v pikaur) ]; then
    echo -e "Updating AUR packages..."
    pikaur -Sayu
  fi
  if [ $(command -v aura) ]; then
    echo -e "Updating AUR packages..."
    aura -Au
  fi
}
  

if [ "$PACUP_MOD" == "pacman" ]; then
  sudo echo -n
  if [ $? != 0 ]; then
    echo -e "\nPacman command requires root privileges.\nPlease try again.\n"
    sudo echo -n
    if [ $? != 0 ]; then
    echo -e "\nExecution terminated because privilege elevation failed."
    exit 1
    fi
  fi
  PACUP_PACMAN
  exit 0
fi

sudo echo -n
if [ $? != 0 ]; then
  echo -e "\nRequesting root privileges.\nPlease try again.\n"
  sudo echo -n
  if [ $? != 0 ]; then
    echo -e "\nExecution terminated because privilege elevation failed."
    exit 1
  fi
fi

PACUP_PACMAN
PACUP_SYS
PACUP_AUR_ROOT

echo -e "\nDone!"
exit 0
