#!/bin/bash

function usage() {
  cat <<EOM
使用方法: $(basename "$0") [OPTION]...
    -p          Pacmanのみ実行
    -y          'y'の入力をスキップします
    -h          ヘルプを表示します
EOM
}

while (($#>0)); do
  case $1 in
    p|-p|--pacman)
      PACUP_MOD="pacman"
      ;;
    y|-y|--yes)
      PACUP_YES="yes"
      ;;
    h|-h|--help)
      usage
      exit 0
      ;;
    *)
      usage
      exit 1
      ;;
  esac
  shift
done

function PACUP_SYS() {
  : #SYS
}

function PACUP_PACMAN() {
  sudo pacman -Syu
  $PACUP_YES|sudo pacman -Rnsc $(pacman -Qtdq)  
}

if [ "$PACUP_MOD" == "pacman" ]; then
   PACUP_PACMAN
  if [ $? != 0 ]; then
    echo -e "\nPacmanコマンドの実行はRoot(管理者)権限を要求します｡\nもう一度お試しください｡\n"
    PACUP_PACMAN
  fi
  exit 0
fi

#FPK
PACUP_SYS
if [ $? != 0 ]; then
  echo -e "\nRoot(管理者)権限を要求しています｡\nもう一度お試しください｡\n"
  PACUP_SYS
  if [ $? != 0 ]; then
    echo -e "\n権限の昇格に失敗したため､ 実行を終了しました｡"
    exit 1
  fi
fi
PACUP_PACMAN
exit 0
